const mongoose = require("mongoose");
require("dotenv").config();
const Product = require("./models/Product");

mongoose.connect(process.env.MONGO_URI)
  .then(() => console.log("MongoDB connected for seeding"))
  .catch((err) => console.log(err));

const products = [
  {
    id: 1,
    name: "Striped Flutter Sleeve Overlap Collar Peplum Hem ",
    category: "women",
    image: "https://res.cloudinary.com/lzk1dhnu/image/upload/v1787307928/ecommerce-products/product_1.png",
    new_price: 50.0,
    old_price: 80.5,
    quantity: 10,
  },
  {
    id: 2,
    name: "Striped Flutter Sleeve Overlap Peplum Hem Frock",
    category: "women",
    image: "https://res.cloudinary.com/lzk1dhnu/image/upload/v1787307929/ecommerce-products/product_2.png",
    new_price: 85.0,
    old_price: 120.5,
    quantity: 20,
  },
  {
    id: 3,
    name: "Striped Flutter Sleeve Overlap Collar Peplum Hem ",
    category: "women",
    image: "https://res.cloudinary.com/lzk1dhnu/image/upload/v1787307931/ecommerce-products/product_3.png",
    new_price: 60.0,
    old_price: 100.5,
    quantity: 10,
  },
  {
    id: 4,
    name: "Striped Flutter Sleeve Overlap Collar Peplum Hem",
    category: "women",
    image: "https://res.cloudinary.com/lzk1dhnu/image/upload/v1787307932/ecommerce-products/product_4.png",
    new_price: 100.0,
    old_price: 150.0,
    quantity: 7,
  },
  {
    id: 5,
    name: "Striped Flutter Sleeve Overlap Collar Peplum Hem",
    category: "women",
    image: "https://res.cloudinary.com/lzk1dhnu/image/upload/v1787307934/ecommerce-products/product_5.png",
    new_price: 85.0,
    old_price: 120.5,
    quantity: 5,
  },
  {
    id: 6,
    name: "Striped Flutter Sleeve Overlap Collar Peplum Hem ",
    category: "women",
    image: "https://res.cloudinary.com/lzk1dhnu/image/upload/v1787307935/ecommerce-products/product_6.png",
    new_price: 85.0,
    old_price: 120.5,
    quantity: 0,
  },
  {
    id: 7,
    name: "Striped Flutter Sleeve Overlap Collar Peplum Hem",
    category: "women",
    image: "https://res.cloudinary.com/lzk1dhnu/image/upload/v1787307937/ecommerce-products/product_7.png",
    new_price: 85.0,
    old_price: 120.5,
    quantity: 9,
  },
  {
    id: 8,
    name: "Striped Flutter Sleeve Overlap Collar Peplum Hem ",
    category: "women",
    image: "https://res.cloudinary.com/lzk1dhnu/image/upload/v1787307938/ecommerce-products/product_8.png",
    new_price: 85.0,
    old_price: 120.5,
    quantity: 11,
  },
  {
    id: 9,
    name: "Striped Flutter Sleeve Overlap Collar Peplum Hem ",
    category: "women",
    image: "https://res.cloudinary.com/lzk1dhnu/image/upload/v1787307939/ecommerce-products/product_9.png",
    new_price: 85.0,
    old_price: 120.5,
    quantity: 14,
  },
  {
    id: 10,
    name: "Striped Flutter Sleeve Overlap Collar Peplum Hem ",
    category: "women",
    image: "https://res.cloudinary.com/lzk1dhnu/image/upload/v1787307940/ecommerce-products/product_10.png",
    new_price: 85.0,
    old_price: 120.5,
    quantity: 0,
  },
  {
    id: 11,
    name: "Striped Flutter Sleeve Overlap Collar Peplum Hem",
    category: "women",
    image: "https://res.cloudinary.com/lzk1dhnu/image/upload/v1787307941/ecommerce-products/product_11.jpg",
    new_price: 85.0,
    old_price: 120.5,
    quantity: 0,
  },
  {
    id: 12,
    name: "Striped Flutter Sleeve Overlap Collar Peplum Hem ",
    category: "women",
    image: "https://res.cloudinary.com/lzk1dhnu/image/upload/v1787307942/ecommerce-products/product_12.png",
    new_price: 85.0,
    old_price: 120.5,
    quantity: 2,
  },
  {
    id: 13,
    name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    category: "men",
    image: "https://res.cloudinary.com/lzk1dhnu/image/upload/v1787307943/ecommerce-products/product_13.png",
    new_price: 85.0,
    old_price: 120.5,
    quantity: 7,
  },
  {
    id: 14,
    name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    category: "men",
    image: "https://res.cloudinary.com/lzk1dhnu/image/upload/v1787307944/ecommerce-products/product_14.png",
    new_price: 85.0,
    old_price: 120.5,
    quantity: 8,
  },
  {
    id: 15,
    name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    category: "men",
    image: "https://res.cloudinary.com/lzk1dhnu/image/upload/v1787307945/ecommerce-products/product_15.png",
    new_price: 85.0,
    old_price: 120.5,
    quantity: 10,
  },
  {
    id: 16,
    name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    category: "men",
    image: "https://res.cloudinary.com/lzk1dhnu/image/upload/v1787307946/ecommerce-products/product_16.png",
    new_price: 85.0,
    old_price: 120.5,
    quantity: 10,
  },
  {
    id: 17,
    name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    category: "men",
    image: "https://res.cloudinary.com/lzk1dhnu/image/upload/v1787307947/ecommerce-products/product_17.png",
    new_price: 85.0,
    old_price: 120.5,
    quantity: 0,
  },
  {
    id: 18,
    name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    category: "men",
    image: "https://res.cloudinary.com/lzk1dhnu/image/upload/v1787307948/ecommerce-products/product_18.png",
    new_price: 85.0,
    old_price: 120.5,
    quantity: 10,
  },
  {
    id: 19,
    name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    category: "men",
    image: "https://res.cloudinary.com/lzk1dhnu/image/upload/v1787307949/ecommerce-products/product_19.png",
    new_price: 85.0,
    old_price: 120.5,
    quantity: 10,
  },
  {
    id: 20,
    name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    category: "men",
    image: "https://res.cloudinary.com/lzk1dhnu/image/upload/v1787307951/ecommerce-products/product_20.png",
    new_price: 85.0,
    old_price: 120.5,
    quantity: 10,
  },
  {
    id: 21,
    name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    category: "men",
    image: "https://res.cloudinary.com/lzk1dhnu/image/upload/v1787307952/ecommerce-products/product_21.png",
    new_price: 85.0,
    old_price: 120.5,
    quantity: 9,
  },
  {
    id: 22,
    name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    category: "men",
    image: "https://res.cloudinary.com/lzk1dhnu/image/upload/v1787307953/ecommerce-products/product_22.png",
    new_price: 85.0,
    old_price: 120.5,
    quantity: 10,
  },
  {
    id: 23,
    name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    category: "men",
    image: "https://res.cloudinary.com/lzk1dhnu/image/upload/v1787307954/ecommerce-products/product_23.png",
    new_price: 85.0,
    old_price: 120.5,
    quantity: 10,
  },
  {
    id: 24,
    name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    category: "men",
    image: "https://res.cloudinary.com/lzk1dhnu/image/upload/v1787307955/ecommerce-products/product_24.png",
    new_price: 85.0,
    old_price: 120.5,
    quantity: 10,
  },
  {
    id: 25,
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    category: "kid",
    image: "https://res.cloudinary.com/lzk1dhnu/image/upload/v1787307956/ecommerce-products/product_25.png",
    new_price: 85.0,
    old_price: 120.5,
    quantity: 1,
  },
  {
    id: 26,
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    category: "kid",
    image: "https://res.cloudinary.com/lzk1dhnu/image/upload/v1787307957/ecommerce-products/product_26.png",
    new_price: 85.0,
    old_price: 120.5,
    quantity: 3,
  },
  {
    id: 27,
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    category: "kid",
    image: "https://res.cloudinary.com/lzk1dhnu/image/upload/v1787307958/ecommerce-products/product_27.png",
    new_price: 85.0,
    old_price: 120.5,
    quantity: 10,
  },
  {
    id: 28,
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    category: "kid",
    image: "https://res.cloudinary.com/lzk1dhnu/image/upload/v1787307959/ecommerce-products/product_28.png",
    new_price: 85.0,
    old_price: 120.5,
    quantity: 30,
  },
  {
    id: 29,
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    category: "kid",
    image: "https://res.cloudinary.com/lzk1dhnu/image/upload/v1787307960/ecommerce-products/product_29.png",
    new_price: 85.0,
    old_price: 120.5,
    quantity: 0,
  },
  {
    id: 30,
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    category: "kid",
    image: "https://res.cloudinary.com/lzk1dhnu/image/upload/v1787307961/ecommerce-products/product_30.png",
    new_price: 85.0,
    old_price: 120.5,
    quantity: 1,
  },
  {
    id: 31,
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    category: "kid",
    image: "https://res.cloudinary.com/lzk1dhnu/image/upload/v1787307963/ecommerce-products/product_31.png",
    new_price: 85.0,
    old_price: 120.5,
    quantity: 16,
  },
  {
    id: 32,
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    category: "kid",
    image: "https://res.cloudinary.com/lzk1dhnu/image/upload/v1787307964/ecommerce-products/product_32.png",
    new_price: 85.0,
    old_price: 120.5,
    quantity: 2,
  },
  {
    id: 33,
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    category: "kid",
    image: "https://res.cloudinary.com/lzk1dhnu/image/upload/v1787307965/ecommerce-products/product_33.png",
    new_price: 85.0,
    old_price: 120.5,
    quantity: 10,
  },
  {
    id: 34,
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    category: "kid",
    image: "https://res.cloudinary.com/lzk1dhnu/image/upload/v1787307966/ecommerce-products/product_34.png",
    new_price: 85.0,
    old_price: 120.5,
    quantity: 10,
  },
  {
    id: 35,
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    category: "kid",
    image: "https://res.cloudinary.com/lzk1dhnu/image/upload/v1787307967/ecommerce-products/product_35.png",
    new_price: 85.0,
    old_price: 120.5,
    quantity: 16,
  },
  {
    id: 36,
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    category: "kid",
    image: "https://res.cloudinary.com/lzk1dhnu/image/upload/v1787307968/ecommerce-products/product_36.png",
    new_price: 85.0,
    old_price: 120.5,
    quantity: 18,
  },
];

const seedDB = async () => {
  try {
    await Product.deleteMany({});
    await Product.insertMany(products);
    console.log("Products seeded successfully!");
    process.exit();
  } catch (error) {
    console.log("Seeding error:", error);
    process.exit(1);
  }
};

seedDB();